version: '3.7'
services:

  # java 8
  # TODO JAVA 有问题始终是无法进行成功运行jar
  java:
    image: java:8-jdk-alpine
    command: java -jar /app.jar
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app.jar

    # links:
    #   - mysql
    # 
    # environment:
    #   - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"

  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
    links:
      - java:java
      
