version: '3.7'
services:

  # # # mysql5.7
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    # 将本地data绑定
    volumes:
      - ./data/mysql:/var/lib/mysql
      
  # java 8
  java:
    image: java:8-jdk-alpine
    command: java -jar /app.jar
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app.jar

    # 在容器中运行 java -jar /app.jar
    command: 
      java -jar /app.jar

    links:
      - mysql

    # environment:
    #   - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"

  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    links:
      - java:java
      
