version: '3.7'
services:

  # # # mysql5.7
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "oadb"
      MYSQL_USER: "oadb"
      MYSQL_PASSWORD: "123456"

    # 允许远程访问
    command: 
      - "--default-authentication-plugin=mysql_native_password"
      # 导入 sql
      - "--init-file=/oadb.sql"
      # - "mysql -h 172.17.0.1 -u root -p12345 oadb< /oadb.sql"

    # 将本地data绑定
    volumes:
      - ./sqldata/mysql:/var/lib/mysql
      - ./sqldata/mysql/oadb.sql:/oadb.sql
      
  # java 8
  # TODO JAVA 有问题始终是无法进行成功运行jar
  java:
    image: java
    command: java -jar /app.jar
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app.jar

    links:
      - mysql

    # environment:
    #   - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"

  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
    links:
      - java:java
      
