version: '3.7'
services:

  # # # mysql5.7
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "oadb"  # 数据库名
      # MYSQL_USER: "oadb"      # 数据库登录用户名
      # MYSQL_PASSWORD: "123456"    # 数据库登录密码

    # 允许远程访问
    command: 
      - "--default-authentication-plugin=mysql_native_password"
      # - "mysql -h 172.17.0.1 -u root -p123456 oadb< /oadb.sql"
      
    # 将本地data绑定
    volumes:
      - ./sqldata/mysql:/var/lib/mysql
      - ./oadb.sql:/oadb.sql
      
  # java 8
  java:
    image: java
    command: java -jar /app.jar
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app.jar

    links:
      - mysql

    # environment:
    #   - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
    environment:
      - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
      - JAVA_OPTS="-Dspring.profiles.active=prod"
      - JAVA_OPTS="-Dspring.datasource.url=jdbc:mysql://mysql:3306/oadb?useUnicode=true&characterEncoding=utf8&useSSL=false"

  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
    links:
      - java:java
      
